version: "3"

services:
  mysql:
    container_name: order_service_databse
    build: ./database
    ports:
      - 3306:3306
    restart: always

  app:
    build: ./
    container_name: order_service_app
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 8888:8888
